services:
  nginx:
    image: "nginx:1.27.1"
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - on-premise
      - cloud

  on-premise:
    image: php:8.3.10-alpine
    working_dir: "/app"
    volumes:
      - ./on-premise/:/app/
    command: "php artisan serve --host 0.0.0.0"

  cloud:
    image: php:8.3.10-alpine
    working_dir: "/app"
    volumes:
      - ./cloud/:/app/
    command: "php artisan serve --host 0.0.0.0"